### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by mayagao**
screen shot 2015-11-09 at 12 55 20 pm
screen shot 2015-11-09 at 2 27 52 pm

cc @mikelmaron  @lxbarth

### CODE REVIEW

**Comment by mikelmaron** [comment]
@d3netxer check out this refreshed design!

**Comment by mayagao** [comment]
fixed link to google fonts

**Comment by lxbarth** [comment]
This is awesome. Let's merge! @d3netxer ?

**Comment by d3netxer** [comment]
alright, I'll work on merging that pull request tonight, and David S. can work on sending an update to HOT osm listserv tomorrow (We are already started planning an OSM GeoWeek update e-mail, but should should wait until after this new template is merge. Let's shoot for that.

**Comment by d3netxer** [comment]
accepting pull request. Thank you for your contributions. I will proceed with tweaks (fixing Guides link on homepage, I'm not sure if we are publishing the Social Media Kit online yet). It might be nice to have a little green twitter bird image on the top right where people can tweet easily.

**Pull request merged**
